name: Publish to Chrome Web Store

# Run this workflow only when a new tag is pushed
on:
  push:
    tags:
      - 'v*' # Runs on tags like v1.0, v1.2.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Zip extension
        run: zip -r extension.zip ./dist

      - name: Upload to Chrome Web Store
        uses: furkanipek/chrome-extension-action@v1.0.1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          extension-id: ${{ secrets.EXTENSION_ID }}

          extension-file: extension.zip

          # Set to 'true' to auto-publish after uploading.
          # 'false' will upload it as a draft.
          publish: false
