name: Publish to Chrome Web Store

# Run this workflow only when a new tag is pushed
on:
  push:
    tags:
      - 'v*' # Runs on tags like v1.0, v1.2.1, etc.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Zip extension
        run: cd dist && zip -r ../extension.zip . && cd ..

      - name: Upload to Chrome Web Store
        run: npm run upload
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          EXTENSION_FILE: extension.zip
          PUBLISH: false
